[book]
authors = ["Mythfall Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Mythfall Wiki"

[output.html]
no-section-label = true

[preprocessor.tera]
command = "mdbook-tera --json ./src/wikidata.json"